# Generated by Django 5.0 on 2023-12-27 18:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Blac', '0003_product_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Product',
        ),
    ]
